/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectNER2;

import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author alanj
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.getContentPane().setBackground(Color.GRAY);
        mensajes();
        setLocationRelativeTo(null); //* Para todas las ventanas ///* locacion al centro de la pantalla
        setIconImage(new ImageIcon(getClass().getResource("/ProyectNER2/icon/IconWindow.png")).getImage()); //*Icono del programa 
    }

    void mensajes() {
        Random a = new Random();
        String texto;
        int b = a.nextInt(8) + 1;

        switch (b) {
            case 1:
                texto = "Hola, bienvenido";
                lbConsejos.setText(texto);
                break;
            case 2:
                texto = "Desarrollado por alumnos del CECYETM";
                lbConsejos.setText(texto);
                break;
            case 3:
                texto = "Te gusta el programa?";
                lbConsejos.setText(texto);
                break;
            case 4:
                texto = "Tienes alguna sugerencia?";
                lbConsejos.setText(texto);
                break;
            case 5:
                texto = "Te sientes bien?";
                lbConsejos.setText(texto);
                break;
            case 6:
                texto = "Que tal tu dia?";
                lbConsejos.setText(texto);
                break;
            case 7:
                texto = "Buenas xd";
                lbConsejos.setText(texto);
                break;
            case 8:
                texto = "Software libre?";
                lbConsejos.setText(texto);
                break;
            case 9:
                texto = "Gracias por elegir nuestro software";
                lbConsejos.setText(texto);
                break;
            default:
                texto = "Programa hecho por Alann Estrada y Lex Hernandez";
                lbConsejos.setText(texto);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnNC = new javax.swing.JButton();
        btnNCT = new javax.swing.JButton();
        btnPro = new javax.swing.JButton();
        btnDevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lbConsejos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        btnNC.setBackground(new java.awt.Color(102, 102, 255));
        btnNC.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnNC.setForeground(new java.awt.Color(255, 255, 255));
        btnNC.setText("Nuevo Cliente");
        btnNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCActionPerformed(evt);
            }
        });

        btnNCT.setBackground(new java.awt.Color(102, 102, 255));
        btnNCT.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnNCT.setForeground(new java.awt.Color(255, 255, 255));
        btnNCT.setText("Nuevo Cliente Tienda");
        btnNCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCTActionPerformed(evt);
            }
        });

        btnPro.setBackground(new java.awt.Color(102, 102, 255));
        btnPro.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnPro.setForeground(new java.awt.Color(255, 255, 255));
        btnPro.setText("Productos");
        btnPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProActionPerformed(evt);
            }
        });

        btnDevo.setBackground(new java.awt.Color(102, 102, 255));
        btnDevo.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnDevo.setForeground(new java.awt.Color(255, 255, 255));
        btnDevo.setText("Reportes");
        btnDevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(102, 102, 255));
        btnSalir.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/Iconos/1233.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lbConsejos.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(82, 208, 83));
        jLabel1.setText("VENTANA PRINCIPAL BIENVENIDO!");

        jMenu1.setForeground(new java.awt.Color(82, 208, 83));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/icon/IconWindow.png"))); // NOI18N
        jMenu1.setText("NERV");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Crear Clientes Nuevos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Crear Clientes Tiendas Nuevos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Productos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Reportes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbConsejos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNC)
                            .addComponent(btnPro))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDevo)
                            .addComponent(btnNCT)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNC)
                    .addComponent(btnNCT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPro)
                    .addComponent(btnDevo))
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lbConsejos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void btnNCActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        Ing_Clientes IG = new Ing_Clientes();
        IG.setVisible(true);
        dispose();
    }                                     

    private void btnNCTActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        Ing_Cli_Tiendas IGT = new Ing_Cli_Tiendas();
        IGT.setVisible(true);
        dispose();
    }                                      

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void btnProActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        Productos PRO = new Productos();
        PRO.setVisible(true);
        dispose();
    }                                      

    private void btnDevoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Reporte DEVO = new Reporte();
        DEVO.setVisible(true);
        dispose();
    }                                       

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:

    }                                      

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Ing_Cli_Tiendas IGT = new Ing_Cli_Tiendas();
        IGT.setVisible(true);
        dispose();
    }                                          

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Productos PRO = new Productos();
        PRO.setVisible(true);
        dispose();
    }                                          

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        // TODO add your handling code here:
        Reporte DEVO = new Reporte();
        DEVO.setVisible(true);
        dispose();
    }                                          

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Ing_Clientes IG = new Ing_Clientes();
        IG.setVisible(true);
        dispose();
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDevo;
    private javax.swing.JButton btnNC;
    private javax.swing.JButton btnNCT;
    private javax.swing.JButton btnPro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lbConsejos;
    // End of variables declaration                   
}

