/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectNER2;

import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
/*import java.util.logging.Level;
import java.util.logging.Logger;*/

/**
 *
 * @author Alumno16SC
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    conectar cc = new conectar();
    Connection cn =cc.conexion();
    public MenuAdmin() {
        initComponents();
        this.getContentPane().setBackground(Color.GRAY);
        setLocationRelativeTo(null); //* Para todas las ventanas
        setIconImage(new ImageIcon(getClass().getResource("/ProyectNER2/icon/IconWindow.png")).getImage()); //*Icono del programa 
        mensajes();
    }
    void mensajes() {
        Random a = new Random();
        String texto;
        int b = a.nextInt(8) + 1;

        switch (b) {
            case 1:
                texto = "Hola, bienvenido";
                lbConsejos.setText(texto);
                break;
            case 2:
                texto = "Desarrollado por alumnos del CECYETM";
                lbConsejos.setText(texto);
                break;
            case 3:
                texto = "Te gusta el programa?";
                lbConsejos.setText(texto);
                break;
            case 4:
                texto = "Tienes alguna sugerencia?";
                lbConsejos.setText(texto);
                break;
            case 5:
                texto = "Te sientes bien?";
                lbConsejos.setText(texto);
                break;
            case 6:
                texto = "Que tal tu dia?";
                lbConsejos.setText(texto);
                break;
            case 7:
                texto = "Buenas xd";
                lbConsejos.setText(texto);
                break;
            case 8:
                texto = "Software libre?";
                lbConsejos.setText(texto);
                break;
            case 9:
                texto = "Gracias por elegir nuestro software";
                lbConsejos.setText(texto);
                break;
            default:
                texto = "Programa hecho por Alann Estrada y Lex Hernandez";
                lbConsejos.setText(texto);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnAUN = new javax.swing.JButton();
        btnET = new javax.swing.JButton();
        btnCT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbConsejos = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AUN = new javax.swing.JMenuItem();
        ET = new javax.swing.JMenuItem();
        CDTLT = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Admin");

        btnAUN.setBackground(new java.awt.Color(102, 102, 255));
        btnAUN.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnAUN.setForeground(new java.awt.Color(255, 255, 255));
        btnAUN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/Iconos/editar-removebg-preview.png"))); // NOI18N
        btnAUN.setText("Agregar Nuevo Usuario");
        btnAUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAUNActionPerformed(evt);
            }
        });

        btnET.setBackground(new java.awt.Color(102, 102, 255));
        btnET.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnET.setForeground(new java.awt.Color(255, 255, 255));
        btnET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/Iconos/eliminar1-removebg-preview.png"))); // NOI18N
        btnET.setText("Eliminar tablas");
        btnET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnETActionPerformed(evt);
            }
        });

        btnCT.setBackground(new java.awt.Color(102, 102, 255));
        btnCT.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnCT.setForeground(new java.awt.Color(255, 255, 255));
        btnCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/Iconos/1668640064672-removebg-preview.png"))); // NOI18N
        btnCT.setText("Contenido de todas las tablas");
        btnCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(82, 208, 83));
        jLabel1.setText("ADMIN VENTANA \nBienvenido!");

        lbConsejos.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/icon/IconWindow.png"))); // NOI18N
        jMenu1.setText("NERV");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        AUN.setText("Agregar Nuevo Usuario");
        AUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AUNActionPerformed(evt);
            }
        });
        jMenu1.add(AUN);

        ET.setText("Eliminar tablas");
        ET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ETActionPerformed(evt);
            }
        });
        jMenu1.add(ET);

        CDTLT.setText("Contenido de todas las tablas");
        CDTLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDTLTActionPerformed(evt);
            }
        });
        jMenu1.add(CDTLT);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbConsejos, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnCT)
                    .addComponent(btnET)
                    .addComponent(btnAUN))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(btnAUN)
                .addGap(18, 18, 18)
                .addComponent(btnET)
                .addGap(18, 18, 18)
                .addComponent(btnCT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lbConsejos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void btnETActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        //*TRUNCATE TABLE tbl_usuarios;
        int salida=JOptionPane.showConfirmDialog(null, "Estas seguro de borrar el contenido de las tablas?", "Seleccione una opcion",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(salida==0){
           String sql,sqll,sqlll,sqql;
           sql="TRUNCATE TABLE clientes";
           sqll="TRUNCATE TABLE clientestienda";
           sqlll="TRUNCATE TABLE productos";
           sqql="TRUNCATE TABLE reportes";
           PreparedStatement psd;
            try {
                psd = cn.prepareStatement(sql);
                psd.executeUpdate();
                psd= cn.prepareStatement(sqll);
                psd.executeUpdate();
                psd= cn.prepareStatement(sqlll);
                psd.executeUpdate();
                psd= cn.prepareStatement(sqql);
                psd.executeUpdate();
                JOptionPane.showMessageDialog(null, "Eliminado con exito");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al eliminar"+ex);
            }
        }
        //*reparar error y poner iconos
    }                                     

    private void CDTLTActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        ContenidoDeTabla CDT = new ContenidoDeTabla();
        CDT.setVisible(true);
        dispose();
    }                                     

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void AUNActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
       AgregarUsuarioADMIN AUN = new AgregarUsuarioADMIN();
       AUN.setVisible(true);
       dispose();
    }                                   

    private void ETActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
       
        //*Eliminar tablas
    }                                  

    private void btnAUNActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        AgregarUsuarioADMIN AUN = new AgregarUsuarioADMIN();
        AUN.setVisible(true);
        dispose();
    }                                      

    private void btnCTActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        ContenidoDeTabla CDT = new ContenidoDeTabla();
        CDT.setVisible(true);
        dispose();
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem AUN;
    private javax.swing.JMenuItem CDTLT;
    private javax.swing.JMenuItem ET;
    private javax.swing.JButton btnAUN;
    private javax.swing.JButton btnCT;
    private javax.swing.JButton btnET;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbConsejos;
    // End of variables declaration                   
}
