/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectNER2;


import java.awt.Color;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
/*import java.util.logging.Level;
import java.util.logging.Logger;*/
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;*/

/**
 *
 * @author alanj
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form MAIN
     */
    
    String ID;
    conectar cc = new conectar();
    Connection cn =cc.conexion();
    DefaultTableModel model;
    public Productos() {
        initComponents();
        this.getContentPane().setBackground(Color.gray);
        limpiar();
        desbloquear();
        cargar("");
        RellenarCBOXCliente("clientestienda","NomCliente",cb_EmpresasOCli);
        RellenarCBOXCliente("clientes", "NomCliente", cb_EmpresasOCli);
        setLocationRelativeTo(null); //* Para todas las ventanas
        setIconImage(new ImageIcon(getClass().getResource("/ProyectNER2/icon/IconWindow.png")).getImage()); //*Icono del programa 
    }
    
    public void RellenarCBOXCliente(String tabla, String valor, JComboBox combo){
        String sql;
        sql="SELECT * FROM "+tabla;
        Statement st;
        ResultSet rs;
        try{
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            while(rs.next()){
                cb_EmpresasOCli.addItem(rs.getString(valor));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error en MYSQL");
        }
        
    }
    
    void cargar(String valor){
        String [] titulos = {"ID","Cliente","Tipo","Marca","Cantidad","CostoTOT","CostoXPZ"};
        String [] registros = new String[8];
        
        String sqsl = "SELECT * FROM productos WHERE CONCAT (ID,'', Cliente,'', Tipo,'', Marca,'',Cantidad,'',CostoTOT,'',CostoXPZ) LIKE '%"+valor+"%'";
        
        model = new DefaultTableModel(null,titulos);
       
        
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sqsl);
            
            while(rs.next()){
                registros[0]=rs.getString("ID");
                registros[1]=rs.getString("Cliente");
                registros[2]=rs.getString("Tipo");
                registros[3]=rs.getString("Marca");
                registros[4]=rs.getString("Cantidad");
                registros[5]=rs.getString("CostoTOT");
                registros[6]=rs.getString("CostoXPZ");
                
                model.addRow(registros);
            }
            tb_productos.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    
    void limpiar(){
        cbElectrodomesticos.setSelectedIndex(0);
        t_marca.setText("");
        t_cantidad.setText("");
        t_costoTOT.setText("");
        
        aux.setText("");
    }
    
    void desbloquear(){
        cbElectrodomesticos.setEnabled(true);
        t_marca.setEnabled(true);
        t_cantidad.setEnabled(true);
        t_costoTOT.setEnabled(true);
        t_costoXPZ.setEnabled(false);
        
        btnNuevo.setEnabled(false);
        btnCrear.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnSalir.setEnabled(false);
     }

    void bloquear(){
        cbElectrodomesticos.setEnabled(false);
        t_marca.setEnabled(false);
        t_cantidad.setEnabled(false);
        t_costoTOT.setEnabled(false);
        t_costoXPZ.setEnabled(false);
        
        btnNuevo.setEnabled(true);
        btnCrear.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnSalir.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t_datos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_productos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        aux = new javax.swing.JTextField();
        btnMostrarTodo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        JPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        t_costoXPZ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_marca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_cantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_costoTOT = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        cbElectrodomesticos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cb_EmpresasOCli = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        t_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(t_datos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Productos");

        tb_productos.setBackground(java.awt.Color.gray);
        tb_productos.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        tb_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tb_productos);

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(82, 208, 83));
        jLabel8.setText("Buscar");

        aux.setText("Buscar En La Tabla");
        aux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auxActionPerformed(evt);
            }
        });
        aux.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                auxKeyReleased(evt);
            }
        });

        btnMostrarTodo.setBackground(new java.awt.Color(102, 102, 255));
        btnMostrarTodo.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnMostrarTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarTodo.setText("Mostrar Todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(102, 102, 255));
        btnBorrar.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/Iconos/1668640134791-removebg-preview.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(102, 102, 255));
        btnEditar.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/Iconos/editar-removebg-preview.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        JPanel.setBackground(java.awt.Color.gray);
        JPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(82, 208, 83));
        jLabel6.setText("Costo Por Pieza");

        t_costoXPZ.setText("SeGeneraAutomaticamente");
        t_costoXPZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_costoXPZActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(82, 208, 83));
        jLabel2.setText("Tipo");

        t_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_marcaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(82, 208, 83));
        jLabel3.setText("Marca");

        t_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cantidadActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(82, 208, 83));
        jLabel4.setText("Cantidad");

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(82, 208, 83));
        jLabel5.setText("Costo Total");

        t_costoTOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_costoTOTActionPerformed(evt);
            }
        });

        btnCrear.setBackground(new java.awt.Color(102, 102, 255));
        btnCrear.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/Iconos/listo-removebg-preview.png"))); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(102, 102, 255));
        btnActualizar.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/Iconos/cargar-removebg-preview.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(102, 102, 255));
        btnCancelar.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/Iconos/1233.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(102, 102, 255));
        btnSalir.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/Iconos/1233.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(102, 102, 255));
        btnNuevo.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectNER2/Iconos/1668640064672-removebg-preview.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        cbElectrodomesticos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lavadoras", "Microondas", "Refrigeradores", "Estufas", "Lavadoras", "Aires" }));

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(82, 208, 83));
        jLabel7.setText("Empresa");

        cb_EmpresasOCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(JPanelLayout.createSequentialGroup()
                            .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2))
                            .addGap(26, 26, 26)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(t_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(t_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_costoXPZ, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_costoTOT, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cb_EmpresasOCli, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbElectrodomesticos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_EmpresasOCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbElectrodomesticos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_costoTOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(t_costoXPZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir)
                    .addComponent(btnNuevo)
                    .addComponent(btnActualizar))
                .addGap(22, 22, 22))
        );

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(82, 208, 83));
        jLabel1.setText("Productos NEVR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnBorrar)
                                .addGap(39, 39, 39)
                                .addComponent(btnEditar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(aux, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMostrarTodo)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(421, 421, 421))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(aux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnEditar))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void t_costoXPZActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        t_costoXPZ.transferFocus();
    }                                          

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        bloquear();
        
        String Cliente,Tipo, Marca, Cantidad, CostoTOT, CostoXPZ, XD;
        int CTOT,CANT,SUM;
        Cliente=cb_EmpresasOCli.getSelectedItem().toString();
        Tipo = cbElectrodomesticos.getSelectedItem().toString();
        Marca = t_marca.getText();
        Cantidad = t_cantidad.getText();
        CANT=Integer.parseInt(Cantidad);
        CostoTOT = t_costoTOT.getText();
        CTOT=Integer.parseInt(CostoTOT);
        SUM= CTOT/CANT;
        XD=Integer.toString(SUM);
        t_costoXPZ.setText(XD);
        CostoXPZ = t_costoXPZ. getText();
        
        
        String sql="";
        sql= "INSERT INTO productos (ID,Cliente,Tipo,Marca,Cantidad,CostoTOT,CostoXPZ) VALUES (NULL,?,?,?,?,?,?)";
        try {
            PreparedStatement psd = cn.prepareStatement(sql);
            psd.setString(1, Cliente);
            psd.setString(2, Tipo);
            psd.setString(3, Marca);
            psd.setString(4, Cantidad);
            psd.setString(5, CostoTOT);
            psd.setString(6, CostoXPZ);
            
            int n = psd.executeUpdate();
            if (n>0){
                JOptionPane.showMessageDialog(null, "Registro Guardado Con Exito");
                cargar("");
            }
            
        } catch (SQLException ex) {
            //*Logger.getLogger(Ing_Cli_Tiendas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ocurrio un error inesperado, caracter repetido en base de datos intente de nuevo"+ex);
            desbloquear();
        }
        
        
    }                                        

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        MenuPrincipal home= new MenuPrincipal();
        home.setVisible(true);
        dispose();
        /*
        bloquear();
        BIENVENIDAA home1 = new BIENVENIDAA();
        home1.setVisible(true);
        dispose();
        */
    }                                           

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        MenuPrincipal home= new MenuPrincipal();
        home.setVisible(true);
        dispose();
    }                                        

    private void t_marcaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        t_marca.transferFocus();
    }                                       

    private void t_cantidadActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        t_cantidad.transferFocus();
    }                                          

    private void t_costoTOTActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        t_costoTOT.transferFocus();
    }                                          

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        limpiar();
        desbloquear();
    }                                        

    private void auxActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        cargar("");
        aux.setText("");
    }                                              

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        int fila=tb_productos.getSelectedRow();
        String valor= (String) tb_productos.getValueAt(fila, 0);
        if (fila>=0) {
            try {
                PreparedStatement psd = cn.prepareStatement("DELETE FROM productos WHERE ID='"+valor+"'");
                psd.executeUpdate();
                JOptionPane.showMessageDialog(null, "Eliminado con exito");
                cargar("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al eleminar la tabla");
            }
        }
    }                                         

    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        desbloquear();
        int fila= tb_productos.getSelectedRow();
        if (fila>=0){
            
            ID = tb_productos.getValueAt(fila, 0).toString();
            cb_EmpresasOCli.addItem(tb_productos.getValueAt(fila, 1).toString());
            cbElectrodomesticos.addItem(tb_productos.getValueAt(fila, 2).toString());
            t_marca.setText(tb_productos.getValueAt(fila, 3).toString());
            t_cantidad.setText(tb_productos.getValueAt(fila, 4).toString());
            t_costoTOT.setText(tb_productos.getValueAt(fila, 5).toString());
            t_costoXPZ.setText(tb_productos.getValueAt(fila, 6).toString());
        }
        else{
            JOptionPane.showMessageDialog(null, "Fila no seleccionada");
        }
    }                                         

    private void auxKeyReleased(java.awt.event.KeyEvent evt) {                                
        // TODO add your handling code here:
        cargar(aux.getText());
    }                               

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        //*PreparedStatement std = cn.prepareStatement("UPDATE clientestienda SET (IDTienda,NombreTienda,Direccion,Telefono,Correo,RFC,NombreCargo) VALUES (NULL,?,?,?,?,?,?)");
        int sum,cantidad,costo;
        String Cliente,Tipo, Marca, Cantidad, CostoTOT, CostoXXPZ, CostoXPZ;
        Cliente=cb_EmpresasOCli.getSelectedItem().toString();
        Tipo = cbElectrodomesticos.getSelectedItem().toString();
        Marca = t_marca.getText();
        Cantidad = t_cantidad.getText();
        cantidad=Integer.parseInt(Cantidad);
        CostoTOT = t_costoTOT.getText();
        costo=Integer.parseInt(CostoTOT);
        sum=costo/cantidad;
        CostoXXPZ=Integer.toString(sum);
        t_costoXPZ.setText(CostoXXPZ);
        CostoXPZ= t_costoXPZ.getText();
     
        try {
            PreparedStatement psd = cn.prepareStatement("UPDATE `productos` SET `Cliente`='"+Cliente+"',`Tipo`='"+Tipo+"',`Marca`='"+Marca+"',`Cantidad`='"+Cantidad+"',`CostoTOT`='"+CostoTOT+"',`CostoXPZ`='"+CostoXPZ+"' WHERE `ID`='"+ID+"'");
            psd.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cambio Actualizado");
            cargar("");
            limpiar();
        } catch (SQLException ex) {
            //*Logger.getLogger(Ing_Cli_Tiendas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ocurrio un error inesperado, caracter repetido en base de datos intente de nuevo");
            desbloquear();
        }
    }                                             

    /**
     * @param args the command line arguments
     */
    
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel JPanel;
    private javax.swing.JTextField aux;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbElectrodomesticos;
    private javax.swing.JComboBox<String> cb_EmpresasOCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField t_cantidad;
    private javax.swing.JTextField t_costoTOT;
    private javax.swing.JTextField t_costoXPZ;
    private javax.swing.JTable t_datos;
    private javax.swing.JTextField t_marca;
    private javax.swing.JTable tb_productos;
    // End of variables declaration                   
}

